openapi: 3.0.0
info:
  title: Product REST API
  version: 1.0.0
servers:
  - url: localhost://
paths:
  /080/products/:
    get:
      tags:
        - default
      summary: Get All Products
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
    post:
      tags:
        - default
      summary: Create Product
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                productName: Lenovo Yoga
                productType: Laptop
                productCategory: Electronics
                basePrice: 45000
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /080/products/1:
    get:
      tags:
        - default
      summary: Get Product By ID
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
    put:
      tags:
        - default
      summary: Update Product
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                productName: Lenovo Yoga
                productType: Laptop
                productCategory: Electronics
                basePrice: 45000
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
    delete:
      tags:
        - default
      summary: Delete Product
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
